.eslintrc.json

| Bug fix         | ✔                                                                      |
| Chore            | ✖ …

fix: added dist to lint ignored patterns

---

src/index.ts
src/serverBuilder.ts

| Bug fix         | ✔                                                                  |
| Chore            | ✖ …

fix(server): set readiness prob to ready

---

package-lock.json
package.json

feat(configurations): added pretty-quick integration to pre-commit hook

---

src/serverBuilder.ts

chore: remove unnecessary init in serverBuilder.ts

---

config/custom-environment-variables.json
config/default.json
src/serverBuilder.ts

feat: make payload size configurable

---

.editorconfig

feat(configurations): add .editorconfig

---

package-lock.json

build(deps): npm audit

---

.github/workflows/test.yaml

ci: added matrix node version workflow

---

.github/workflows/security.yml

ci: add snyk integration

---

package-lock.json
package.json

build(deps): upgrade to typescript 4.2.4

---

package-lock.json
package.json

feat(deps): upgraded to express-openapi-validator v4.12.9

---

tests/integration/resourceName/resourceName.spec.ts

| Bug fix         | ✔                                                                    |
| Chore            | ✖ …

fix: fixed container registration bug

---

src/index.ts

| Bug fix         | ✔                                                                        |

fix: fixed terminus not found liveness

---

.github/workflows/pull_request.yaml

ci: build docker image

---

.github/workflows/release-on-tag-push.yaml

ci: add postman collection artifact on release

---

package-lock.json
package.json
src/anotherResource/controllers/anotherResourceController.ts
src/anotherResource/models/anotherResourceManager.ts
src/common/constants.ts
src/containerConfig.ts
src/index.ts
src/resourceName/controllers/resourceNameController.ts
src/resourceName/models/resourceNameManager.ts
src/serverBuilder.ts
tests/integration/anotherResource/resourceName.spec.ts
tests/integration/resourceName/resourceName.spec.ts

Get service name from package json

---

helm/templates/route.yaml
helm/values.yaml

| New feature     | ✖|
| Chore            | ✔ …

feat(configurations): route timeout duration

---

helm/templates/deployment.yaml
helm/values.yaml

feat: added helm pull secret support

---

helm/templates/deployment.yaml
helm/values.yaml

chore: add support for ca insertion in helm

---

helm/templates/deployment.yaml

| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore …

fix: liveness port

---

helm/templates/deployment.yaml
helm/values.yaml

chore: make ca paths configureable

---

helm/templates/_helpers.tpl
helm/templates/deployment.yaml

| Bug fix         | ✔                                                                        | …

fix: global pull secret

---

.prettierignore
package-lock.json
package.json
src/index.ts

build(deps): upgrade @map-colonies/eslint-config -> v3.1.0

---

src/resourceName/models/resourceNameManager.ts

refactor: logging as an object

---

src/index.ts
tests/integration/docs/docs.spec.ts
tests/integration/docs/helpers/docsRequestSender.ts

| Tests added     | ✔                                                                        | …

test: added docs testing

---

.github/workflows/build_and_push.yaml

| Chore            | ✔                                                                       |
Add CI to boilerplate

chore: add github ci

---

helm/templates/deployment.yaml
helm/values.yaml

Further information:
Keep only 5 revisions by default.

feat: add revision history limit configuration

---

src/anotherResource/models/anotherResourceManager.ts
src/anotherResource/routes/anotherResourceRouter.ts
src/containerConfig.ts
src/index.ts
src/serverBuilder.ts

refactor: fix c-spell warning

---

helm/templates/deployment.yaml
helm/values.yaml

Support additional containers in the pod as part of the helm deployment

feat(helm): add sidecars support

---

.github/scripts/bump.py
.github/workflows/bump_chart.yaml

| Bug fix         | ✔/✖                                                                        |
| New feature     | ✔/✖                                                                        |
| Breaking change | ✔/✖                                                                        |
| Deprecations    | ✔/✖                                                                        |
| Documentation   | ✔/✖                                                                        |
| Tests added     | ✔/✖                                                                        |
| Chore …

Add bump chart version to github actions

---

.github/workflows/build-and-push.yaml

| Question                | Answer                                                                         |
| New feature     | ✔                                                                       |
| Refactor            | ✔                                                                       |
Add dependency update to chart and refactor naming

refactor: ci

---

.github/workflows/build-and-push.yaml

| Chore            | ✔                                                                      |
Use updated workflows from shared-workflow repository

chore: Update shared workflows

---

package.json

| Bug fix         | ✔                                                                        | …

chore: Update eslint-config version package.json (MAPCO-4099)

---

helm/templates/deployment.yaml

| Bug fix         | ✔                                                               |
Further  information:
Fix the configmap name reference in the deployment

fix: Fix the configmap name reference in the deployment

---

package-lock.json
package.json
src/serverBuilder.ts

| Deprecations    | ✔                                                                        | …

feat: upgraded telemetry version

---

helm/Chart.lock
helm/Chart.yaml
helm/templates/_helpers.tpl

| New feature     | ✔
Further  information:
Using common names functionality from the common lib

feat: Support common names from the common chart

---

.github/workflows/build-and-push.yaml
.github/workflows/pull_request.yaml
.github/workflows/release-on-tag-push.yaml

| Chore            | ✔                                                                       |

chore: match workflows version

---

helm/Chart.lock
helm/Chart.yaml
helm/templates/_helpers.tpl

Reverts MapColonies/ts-server-boilerplate#303

Revert "feat: Support common names from the common chart"

---

helm/Chart.lock
helm/Chart.yaml
helm/templates/_helpers.tpl
helm/templates/deployment.yaml
helm/templates/route.yaml
helm/templates/service.yaml
helm/values.yaml

Reverts MapColonies/ts-server-boilerplate#300

Revert "chore: Integrate initial common library dependency"

---

helm/templates/route.yaml

| Bug fix         | ✔                                                                        | …

fix: changed durationSeconds ref to duration as defined in values.yaml

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build-and-push.yaml
.github/workflows/release-on-tag-push.yaml
.prettierignore
commitlint.config.js

Remove manual files from prettierignore
| Tests added     | ✖ …

style: remove files from prettierignore

---

.github/workflows/pull_request.yaml

| Question        | Answer |
| --------------- | ------ |
| Bug fix         | ✖  |
| New feature     | ✖  |
| Breaking change | ✖  |
| Deprecations    | ✔  |
| Documentation   | ✖  |
| Tests added     | ✖  |
| Chore           | ✖  |

ci: update pull_request.yaml

---

README.md

docs: update readme with information about codeowners

---

.vscode/settings.json

This pull request includes updates to the Visual Studio Code settings to improve code formatting consistency.
* [`.vscode/settings.json`](diffhunk://#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357L3-R5): Added `editor.defaultFormatter` to use `esbenp.prettier-vscode` and set `files.insertFinalNewline` to true.

chore: added more settings for vscode

---

.github/workflows/pull_request.yaml

Increment the pull request workflow version to include a fix in the helm lint shared workflow

ci: Increment the pull request workflow version

---

.swcrc

| Question        | Answer |
| --------------- | ------ |
| Bug fix         | ✖  |
| New feature     | ✖  |
| Breaking change | ✖  |
| Deprecations    | ✖  |
| Documentation   | ✖  |
| Tests added     | ✖  |
| Chore           | ✔  |
Related issues: #XXX , #XXX ...
Closes #XXX ...
Further information:

chore: add json schema ref to .swcrc file

---

.github/workflows/jira-integration.yaml
helm/Chart.lock
helm/Chart.yaml
helm/templates/_helpers.tpl
helm/templates/deployment.yaml
helm/templates/service.yaml
helm/values.yaml

Use mc-labels-and-annotations helm library.

helm: add mc-labels-and-annotations MAPCO-8584
